# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /dayplan
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# Spring配置
spring:
  # 项目名称
  application:
    name: app

  # mysql配置
  datasource:
    url: jdbc:mysql://115.159.42.54:3306/dayplan?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&cachePrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: tR5sW8yB3eH6qM9c
  # redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: pR2mK9sV4tX6bQ8z

mybatis-plus:
  # 配置xml文件位置：classpath -> target/classes
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 打印SQL日志到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  global-config:
    # 关闭mybatis-plus启动图标(banner)
    banner: false

