# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9999
  servlet:
    # 应用的访问路径
    context-path: /dayplan
    # 编码配置
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 100
    threads:
      # tomcat最大线程数，默认为200
      max: 200
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 10
    # 连接超时（毫秒）
    connection-timeout: 30000

# Spring配置
spring:
  # 项目名称
  application:
    name: app
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.159.42.54:3306/dayplan?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&cachePrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: tR5sW8yB3eH6qM9c
  # redis配置
  data:
    redis:
      host: 115.159.42.54
      port: 6379
      password: pR2mK9sV4tX6bQ8z
      database: 0
      timeout: 5s

# 权限过滤
security-data:
  # 是否开启权限过滤
  enable: true
  # 过滤路径
  includePaths:
    - /login
    - /register
    - /captcha
    - /public/**
  # 静态路径
  staticPaths:
  jwt:
    # 密钥
    secret: secret-key
    # 过期时间(秒) 60*60*10
    expire: 36000

# 日志记录
log-data:
  enable: true

# 字典转换
dict-data:
  enable: true

# 数据加密
crypto-data:
  # 是否开启加密
  enable: true
  # 加密算法
  algorithm: SM4
  # 编码方式
  encode: HEX
  # 密钥(对称加密算法)
  password: 4283CKFQ64YUZ7JW
  # 公钥(非对称加密算法)
  publicKey: 02304312172dc80ca2c93999e3d80f839783a5de5ad11e2e0d3c620e3300546150
  # 私钥(非对称加密算法)
  privateKey: 00debc0fad35981a93a25553f8c2ebbff7e148bb07f90233b191b421649c522e9b

# 接口加密
crypto-api:
  # 是否开启加密
  enable: true
  # 加密头标识
  headerFlag: headerFlag
  # 响应加密公钥(非对称加密算法)
  publicKey: 02304312172dc80ca2c93999e3d80f839783a5de5ad11e2e0d3c620e3300546150
  # 请求解密私钥(非对称加密算法)
  privateKey: 00debc0fad35981a93a25553f8c2ebbff7e148bb07f90233b191b421649c522e9b
  # 包含加解密路径(默认 "/*")
  includePaths:
    - /api/**
  # 排除加解密路径
  excludePaths:
    - /api/public/**